### ISSUE TITLE
[enumist] 9월 배움 (9/20~9/30) 

### ISSUE THREAD

**Issue by tea7day** [realgrid/tech-well#3]
### 목표
배운 내용을 동영상으로 제작하여 유투브에 업로드

### 내용

- [ ] Vue 설치 및 Hello World 만들기

**Comment by onlydel** [comment]
공부는 공부고 프로젝트는 프로젝트니까, 배움은 이쪽 이슈로 하지 말고 테크웰 쪽에서 하면 어떨지요?

**Comment by tea7day** [comment]
넵 enumist 저장소에서 진행하겠습니다.

**Comment by onlydel** [comment]
## 조원홍

### 내용
- [*] [동영상 만드는 방법](https://photos.app.goo.gl/oKa8Su8DVUUGJjeQ9)
- [ ] Vue Mastery 튜토리얼 Into Vue.js 리뷰(영상)

**Comment by tea7day** [comment]
종료합니다. 미션을 이루지 못했네요. 10월 1주차는 꼭 성공하겠다는 다짐을 하며 이슈를 종료합니다. -_ㅠ
